spring:
  profiles.active: dev
---
spring:
  profiles: dev
  redis:
    host: localhost
    port: 6379
     
uaa:
  clientId: bcs
  clientSecret: bcs
  uri: https://091998f5-1a50-4bb5-a057-09a2e91a57a9.predix-uaa.run.aws-usw02-pr.ice.predix.io
  clientBase64Token: YmNzOmJjcw==

---
spring:
  profiles: cloud
  datasource:
    test-while-idle: true
          
      
uaa:
  clientId: ${CLIENT_ID}
  clientSecret: ${CLIENT_SECRET}
  clientBase64Token: ${CLIENT_BASE64_TOKEN}
  uri: ${UAA_URI}

---
spring:
  profiles: unit-test

uaa:
  clientId: dangndq-client
  clientSecret: secret
  uri: http://localhost:8888
  clientBase64Token: ZGFuZ25kcS1jbGllbnQ6c2VjcmV0
  name: predix_wts_uaa_dev

---
spring:
  profiles: basic_qa

uaa:
  clientId: bcs
  clientSecret: bcs
  uri: https://a1c749d2-c961-42a7-af0c-0854f45e0713.predix-uaa.run.aws-usw02-pr.ice.predix.io
  clientBase64Token: YmNzOmJjcw==
  name: predix_bcs_uaa_dev

